words = [
    "llm",
    "pkgs",
    "pnpm",
    "rdparty",
    "stdenv",
    "surfingkeys",
    "userchrome",
    "userscripts",
    "userstyle",
    "userstyle's",
    "violentmonkey",
    "xpinstall",
]
